keycloak:
  service:
    type: NodePort
    nodePort: 31111
app-server:
  service:
    type: NodePort
    httpsNodePort: 31112
  keycloak:
    authServerUrl: "http://ldc.skytap.example:31111/auth"
global:
  registry: localhost